[project]
name = "gamestore"
version = "0.1.0"
readme = "README.md"
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[project.scripts]
gamestore = "gamestore.__main__:main"